title: GITHUB TUTORIAL
author: Justin Chong 
email: jcch950607@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Beginning my journey through the version controlling software and 
  hopefully the software engineering or programming career will take 
  me to financial freedom.

# social links
twitter_username: JAoro # DO NOT include the @ character, or else the build will fail!
github_username:  cchsing # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
